# Generated by Django 4.2.5 on 2023-09-06 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candy_name', models.CharField(max_length=50)),
                ('candy_description', models.TextField(default=None, max_length=256, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('retail_cost', models.PositiveIntegerField()),
                ('package_weight_lbs', models.PositiveIntegerField()),
                ('brand_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
