# Generated by Django 4.2.5 on 2023-09-06 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stw_App', '0002_alter_candy_brand_name_alter_candy_candy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='brand_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candy',
            name='candy_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
