# Generated by Django 4.2.5 on 2023-09-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0003_alter_candy_brand_name_alter_candy_candy_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candy',
        ),
    ]
