# Generated by Django 4.2.5 on 2023-09-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stw_App', '0004_delete_candy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('candy_name', models.CharField(max_length=50)),
                ('candy_description', models.TextField(blank=True, max_length=256, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('retail_cost', models.PositiveIntegerField()),
                ('package_weight_lbs', models.PositiveIntegerField()),
                ('seller', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
