# Generated by Django 4.2.5 on 2023-09-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='package_weight_lbs',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='candy',
            name='retail_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
