# Generated by Django 4.2.5 on 2023-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0006_alter_candy_package_weight_lbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='candy_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
