# Generated by Django 4.2.5 on 2023-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0008_alter_candy_candy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='candy_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
