# Generated by Django 4.2.5 on 2023-09-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0009_alter_candy_candy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='sale_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candy',
            name='candy_description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
