# Generated by Django 4.2.5 on 2023-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0010_candy_sale_percent_alter_candy_candy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='sale_percent',
            field=models.PositiveIntegerField(),
        ),
    ]
