# Generated by Django 4.2.5 on 2023-09-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0011_alter_candy_sale_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candy',
            name='sale_percent',
        ),
        migrations.AddField(
            model_name='candy',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
