# Generated by Django 4.2.5 on 2023-09-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0012_remove_candy_sale_percent_candy_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='brand_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
