# Generated by Django 4.2.5 on 2023-09-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0013_candy_brand_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='candy_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='candy',
            name='candy_name',
            field=models.CharField(max_length=128),
        ),
    ]
