# Generated by Django 4.2.5 on 2023-09-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0015_candycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candycomment',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
