# Generated by Django 4.2.5 on 2023-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0016_alter_candycomment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candycomment',
            name='comment',
            field=models.TextField(blank=True, max_length=1028, null=True),
        ),
    ]
