# Generated by Django 4.2.5 on 2023-09-16 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stw_App', '0019_alter_cart_linked_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartObjects',
        ),
    ]
