# Generated by Django 4.2.5 on 2023-09-16 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stw_App', '0020_rename_cart_cartobjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved_Later',
            new_name='SavedLaterObjects',
        ),
    ]
