# Generated by Django 4.2.5 on 2023-09-16 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stw_App', '0021_rename_saved_later_savedlaterobjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartObjects',
            new_name='CartObject',
        ),
        migrations.RenameModel(
            old_name='SavedLaterObjects',
            new_name='SavedLaterObject',
        ),
    ]
