# Generated by Django 4.2.5 on 2023-09-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0022_rename_cartobjects_cartobject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartobject',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='savedlaterobject',
            old_name='items',
            new_name='item',
        ),
    ]
