# Generated by Django 4.2.5 on 2023-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0024_alter_savedlaterobject_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='candy_description',
            field=models.TextField(blank=True, max_length=1028, null=True),
        ),
    ]
