# Generated by Django 4.2.5 on 2023-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0025_alter_candy_candy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='candy_rating',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
