# Generated by Django 4.2.5 on 2023-10-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stw_App', '0026_candy_candy_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='candy_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
